### ISSUE TITLE
Main menu: Dropdown menu on 2nd submenu cannot be selected 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Armani-Chauffeurs#14]
![main menu_02](https://cloud.githubusercontent.com/assets/11186386/6552277/3e02c334-c67f-11e4-9ec9-eead8f279dcf.jpg)

**Comment by dsigue** [comment]
Problem still exist on Mozilla, Chrome and IE 9 to 11

**Comment by arielcebudigital** [comment]
try to clear cache, working in my end.
