### ISSUE TITLE
Our Services Page: Featured image not aligned as per design specs

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Armani-Chauffeurs#23]
![our services_04](https://cloud.githubusercontent.com/assets/11186386/6568632/ec3feb7a-c715-11e4-88a3-8d786720bd99.jpg)

**Comment by arielcebudigital** [comment]
What browser that the featured is not align?

**Comment by dsigue** [comment]
Problem reproducible to all browser.

**Comment by dsigue** [comment]
Verified and tested, its now working fine, so I flag this as FIXED since problem no longer exist. thanks
