### ISSUE TITLE
Mobile device : Cannot do the scroll down , contact Us page main menu cannot be seen nor selected

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Armani-Chauffeurs#34]
1. Occur only on Itouch 5 and Samsung S4

![mobile maine menu_01](https://cloud.githubusercontent.com/assets/11186386/6569009/160528f6-c71d-11e4-91e8-52194813afe9.jpg)

**Comment by dsigue** [comment]
Problem Fixed on Portrait, however when do the landscape view via Samsung S4, the gallery and contact us cannot be seen or cannot do the scroll down anymore.

**Comment by arielcebudigital** [comment]
try to clear cache.

**Comment by dsigue** [comment]
I already done a Clear Cache but problem still exist..

**Comment by arielcebudigital** [comment]
working on our end..
