### ISSUE TITLE
Mobile Device: Designed and styled the gallery image to look good when do the landscape view

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Armani-Chauffeurs#40]
![mobile gallery_01](https://cloud.githubusercontent.com/assets/11186386/6570158/9e8335ac-c730-11e4-8a70-db38e66eeb9d.jpg)

**Comment by arielcebudigital** [comment]
what mobile device did you used?

**Comment by dsigue** [comment]
I did not put which mobile device does the problem occur because it happen to all mobile devices and thus, I will always put specific devices which problem occur. Thanks
