### ISSUE TITLE
Home Page: Need to remove the extra border line on the lower right portion of the lead Ins layout 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Armani-Chauffeurs#5]
![home_01](https://cloud.githubusercontent.com/assets/11186386/6551095/dc11500c-c66d-11e4-90b0-628d22c6f894.jpg)

**Comment by arielcebudigital** [comment]
it's not border, it's part of the dummy image that i used, next time i'll make sure to slice it perfectly. :-)

**Comment by dsigue** [comment]
Please, re-upload correct slice image, this is to prevent seeing the client incorrect slice image. thanks
