### ISSUE TITLE
Home Page: For Clarification:  Does the services items below banner section is limited for only 3 display or not ?  if not, then all items that are set as featured must be displayed

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Armani-Chauffeurs#8]
For Clarification:

Does all services items display is limited or not?
![home_04](https://cloud.githubusercontent.com/assets/11186386/6551290/ed252956-c670-11e4-8f19-f89c18fa132d.jpg)

**Comment by arielcebudigital** [comment]
for leadins slider - yes limit by 3
